### ISSUE TITLE
Can't get Temperature, RTT and pfBlocker to work

### ISSUE THREAD

**Issue by an10bill** [VictorRobellini/pfSense-Dashboard#1]
I've uploaded the plugins to /usr/local/bin and run a 555 chmod on them. I've put the additional config into telegraf in pfsense, and I've imported the json for the garafana dashboard.

Disk, Cpu, Mem, Load, Uptime etc work flawless. Temperature is getting no data. The pfBlocker parts are blank. The gateway RTT is blank, but the interface summary is working. 

All traffic and thruput graphs work as expected.....

Any suggestions as where I might have slipped something in your recipe?

**Comment by VictorRobellini** [comment]
Try executing the plugins from an ssh shell.  They should all return data.  Please include any errors in your reply.

**Comment by an10bill** [comment]
Thnx.... Didn't think of this as a possability.... They all failed, but I also quickly discovered the culprit.... Windows had managed to insert some ^M at the end of all lines.... So i just quickly edited them away and the scripts worked and returned output, so hopefully they will work through telegraf now :-)
