### ISSUE TITLE
Traffic speed is not correct!

### ISSUE THREAD

**Issue by vanthoi** [VictorRobellini/pfSense-Dashboard#11]
I tried to see if anything changed in the query. It is no different from another Dashboard I have. But on the other Dashboard I get the speed of traffic on the right interface.
You can see the Doardboard I have used here:

[pfSense-telegraf.txt](https://github.com/VictorRobellini/pfSense-Dashboard/files/4737291/pfSense-telegraf.txt)

**Comment by vanthoi** [comment]
Sorry you. Because the viewing time is less than 24 hours, it is skewed. If I left the option in 1 hour it was correct. The WAN part alone did not read my WAN port. I have to enter manually, not in the list to choose!

**Comment by VictorRobellini** [comment]
Good point.  The WAN is needs to be entered manually, but it should be a drop down.
