### ISSUE TITLE
Missing some data on dashboard

### ISSUE THREAD

**Issue by DANgerous25** [VictorRobellini/pfSense-Dashboard#12]
Thanks @VictorRobellini for this great work. I've managed to get most of it working, with the exception of 1) temperature sensor data on the dashboard, 2) points on the dashboard map for pfBlocker. I'm very new to this, so beyond checking the log I'm not sure how else to try to diagnose the issue.

I am getting data for both in influxDB, no obvious errors in the telegraf log (in debug mode). If I run the temperature script it outputs.

My setup:

grafana 7.0.3
pfSense 2.4.5-RELEASE
telegraf 0.9_4
influxDB 1.8.0
pfBlockerNG-devel 2.2.5_32

e.g. [N.B. truncated and edited output]

```
> select * from temperature limit 5
name: temperature
time                degrees host                     sensor
----                ------- ----                     ------
1591583660000000000 27.9    myhostname tz0

```
```
> select * from ip_block_log limit 5
name: ip_block_log
time                ASN  AliasName   ClientHostname Dir DstIP         DstPort DuplicateEventStatus FeedName       GeoIP IPEvaluated    IPVersion Interface InterfaceName Protocol ProtocolID ResolvedHostname SrcIP         SrcPort TrackerID  action host                     path
----                ---  ---------   -------------- --- -----         ------- -------------------- --------       ----- -----------    --------- --------- ------------- -------- ---------- ---------------- -----         ------- ---------  ------ ----                     ----
1588600936000000000 null pfB_PRI1_v4 myrouter    out 100.100.100.100 443     +                    ISC_1000_30_v4 Unk   104.196.57.55  4         re0       LAN           TCP-S    6          Unknown          192.168.1.1  61762   1770008919 block  myhostname /var/log/pfblockerng/ip_block.log
```

Any idea where to look next?

**Comment by DANgerous25** [comment]
A reboot of my server that runs grafana/influx DB has fixed it, so looks like a non-issue.

**Comment by DANgerous25** [comment]
A reboot of the server that runs grafana/influx DB has solved the temperature issue (#1 above), but issue #2 persists (no points on the pfBlocker map).

**Comment by VictorRobellini** [comment]
Did you ever get this working?  One thing I noticed is that you are using Grafana 7.0 which may cause some issues.

**Comment by DANgerous25** [comment]
Hi @VictorRobellini , unfortunately not. I think I tried with Grafana 6.7.something as well as that was the first version I tried, same thing. I can't be sure though, it was a while back. I'm not sure how to safely roll back the version now without ruining everything else that I have set up now!

**Comment by VictorRobellini** [comment]
Just to confirm, you are able to see the data in influx with a query (select * from ip_block_log limit 20) but the map in Grafana is not showing the points.

Does the query inspector for the widget in Grafana give any clues?

![image](https://user-images.githubusercontent.com/39597627/85421519-827e3680-b542-11ea-8581-89eb5904e711.png)

**Comment by dsantanu** [comment]
hi @DANgerous25, 
did you able to solve your `ip_block_log` issue yet? How does your `host` filed actually look like in both of the table - FQDN or just the hostname (e.g. `hostname -s`)?

**Comment by OUZYcn** [comment]
@VictorRobellini  
i have similar question about missing data. 

**Machine A**
influxDB 1.8.0
grafana 7.1.3

**Machine B**
pfSense 2.4.5-RELEASE-p1 (amd64)
telegraf 0.9_4
pfBlockerNG-devel 2.1.4_22 (NOT active yet)


i had import your designed Dashboard and set correct Data source but there is none of table/piechard has data showing at all. Then i go to check select one of chart and check "query inspector" and no return data for sure. 
Therefore, i tried add a new dashboard by myself and using same data source. NOW, data is showing as expected. 

So, any idea of why and how-to fix issues?

**Comment by VictorRobellini** [comment]
With pfBlockerNG-devel is not active, what pie charts were you expecting to populate?
 
Which queries work?  Which don't?  Have you set up logging on telegraf to see if the data is being sent?  Did you see any issues or errors? Have you run queries directly from the influxdb to see if the data is present?

Your post does not provide enough information to help you.
