### ISSUE TITLE
Use interface friendlyname for LAN Interfaces

### ISSUE THREAD

**Issue by susadmin** [VictorRobellini/pfSense-Dashboard#14]
I would like to suggest a small improvement where the Lan interfaces graphs use the interface's friendly name instead of the interface. 

So rather than having igb0, igb1, igb2 etc. which are not very meaningful, we can see the descriptions for each interface that have been setup in pfSense. (e.g. LAN, VoIP, VLAN23, ...). I can't quite figure out how to get the tag to display this value. It would be a great help for me as we have lots of LAN interfaces (VLANS) and I could then easily see what traffic was being used without having to refer back to the interface summary.

As a side note, I have added an extra query to the Gateway RTT graph to add ping times for addresses setup in the ping monitor section of Telegraph: 
SELECT mean("average_response_ms") *1000 FROM "ping" WHERE $timeFilter GROUP BY time($__interval), "url" fill(linear)
I hope you will think this is a useful addition.

**Comment by VictorRobellini** [comment]
The problem with friendly names is that the data exists in 2 different measurements in influx.  The network stats come from the telegraf net plugin and the friendlynames come from the interface plugin.  I don't believe it's possible to join the data in influx.  If you can figure it out, I'll be more than happy to add it.

Where did you set up the ping measurement?
