### ISSUE TITLE
Host not being found with existing variable query

### ISSUE THREAD

**Issue by ndom91** [VictorRobellini/pfSense-Dashboard#17]
Hi Victor,

In the provided Grafana dashboard, it wasn't able to find any hosts with your provided tag query.

I modified it a bit to:

```
SHOW TAG VALUES WITH KEY = "host"
```
And it worked again.

Not sure what caused the problem, I don't have 'pf' in my hostname, maybe that was an issue.

**Comment by VictorRobellini** [comment]
"pf" has nothing to do with the hostname. That measurement is populated by the default telegraf pfsense config. What version of pfSense are you running and on what platform?  Is this a fresh install?

Thanks for the heads up

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/pf


```

Connected to http://localhost:8086 version 1.7.10
InfluxDB shell version: 1.7.10
> use pfsense;
Using database pfsense
> show measurements;
name: measurements
name
----
cpu
disk
diskio
dnsbl_log
gateways
interface
ip_block_log
mem
net
netstat
pf
ping
processes
swap
system
temperature
> select * from pf limit 10
name: pf
time                bad-offset bad-timestamp congestion entries fragment host                     inserts ip-option match  memory normalize proto-cksum removals searches short src-limit state-insert state-limit state-mismatch synproxy
----                ---------- ------------- ---------- ------- -------- ----                     ------- --------- -----  ------ --------- ----------- -------- -------- ----- --------- ------------ ----------- -------------- --------
1585272630000000000 0          0             0          469     0        pfSense.home.mystuff 714784  11006     871564 0      0         0           714315   57252010 0     0         3            0           871            0
1585272640000000000 0          0             0          483     0        pfSense.home.mystuff  714829  11006     871618 0      0         0           714345   57252879 0     0         3            0           871            0
```

**Comment by ndom91** [comment]
Strange, didnt work on my end, but I'm running opnsense so maybe thats why.

**Comment by VictorRobellini** [comment]
How does this work on OpenSense?  Are there any other issues?

**Comment by ndom91** [comment]
Nope, after selecting my host via the adjusted query everything else works as intended, it seems. Opnsense is a fork of pfsense.

**Comment by VictorRobellini** [comment]
I'm aware of the fork, I just wasn't sure how different things are.  I'll update the variable and add OpenSense to the tag of the project.

**Comment by chris2k20** [comment]
> Nope, after selecting my host via the adjusted query everything else works as intended, it seems. Opnsense is a fork of pfsense.

I have some errors in the Telegraf Log file, regarding the firewall log files: 

```
E! [inputs.logparser] Error in plugin: open /var/log/pfblockerng/ip_block.log: no such file or directory
E! [inputs.logparser] Error in plugin: open /var/log/pfblockerng/dnsbl.log: no such file or directory
```


How did you enable pfblockerng on your OPNsense?

And 2. how do you add the telegraf additional_config.conf? I didnt saw a option in the GUI. When I added the lines to the /usr/local/etc/telegraf.conf file, they get removed when clicking 'save' in the Webinterface GUI. 

Thank you very much. Very nice project :+1:

**Comment by ndom91** [comment]
@chris2k20 i skipped the pfblockerng part on opnsense unfortunately
