### ISSUE TITLE
Pfblocker IPs Map

### ISSUE THREAD

**Issue by m7md-notifier** [VictorRobellini/pfSense-Dashboard#18]
Hi , everthing is work as expected 

only the map its not show any heat area on it .

**Comment by VictorRobellini** [comment]
Please run through the troubleshooting section and requirements.  Make sure the correct version of pfblocker is installed and check that there's data being populated in your influxdb.

**Comment by VictorRobellini** [comment]
Please run through the troubleshooting and create a new issue with more details if you are still having problems.
