### ISSUE TITLE
IPv6 in telegraf_netifinfo_plugin 

### ISSUE THREAD

**Issue by opswhisperer** [VictorRobellini/pfSense-Dashboard#21]
Could you add IPv6 info to telegraf_netifinfo_plugin so that it can be displayed in the table?

**Comment by opswhisperer** [comment]
actually, its probably in telegraf_pfinterface.php. I could add that but I don't know how that will affect everything else.

**Comment by VictorRobellini** [comment]
Totally untested, but this should work:

`#!/usr/local/bin/php-cgi -f
<?php
require_once("config.inc");
require_once("gwlb.inc");
require_once("interfaces.inc");

$host = gethostname();
$source = "pfconfig";

$iflist = get_configured_interface_with_descr(true);
foreach ($iflist as $ifname => $friendly) {
        $ifinfo =  get_interface_info($ifname);
        $ifstatus = $ifinfo['status'];
        $ifconf = $config['interfaces'][$ifname];
        $ipaddr = get_interface_ip($ifname);
        $subnet = get_interface_subnet($ifname);
        $ipaddr6 = get_interface_ipv6($ifname);
        $subnet6 = get_interface_subnetv6($ifname);
        $realif = get_real_interface($ifname);
        $mac = get_interface_mac($realif);

        if (!isset($ipaddr)){
                $ipaddr = "Unassigned";
        }
        if (!isset($mac)){
                $mac = "Unavailable";
        }
        if (strtolower($ifstatus) == "up"){
                $ifstatus = 1;
        }
        if (strtolower($ifstatus) == "active"){
                $ifstatus = 1;
        }
        if (strtolower($ifstatus) == "no carrier"){
                $ifstatus = 0;
        }
        if (strtolower($ifstatus) == "down"){
                $ifstatus = 0;
        }
        if (!isset($ifstatus)){
                $ifstatus = 2;
        }   

        printf("interface,host=%s,name=%s,ip4_address=%s,ip6_address=%s,mac_address=%s,friendlyname=%s,source=%s status=%s\n",
                $host,
                $realif,
                $ipaddr,
                $ipaddr6,
                $mac,
                $friendly,
                $source,
                $ifstatus
                );
}
?>`

**Comment by opswhisperer** [comment]
The script output looks correct but I'm not seeing the new key in Influx. Is there something I need to do to update the schema?

**Comment by opswhisperer** [comment]
got it also needed
`if (!isset($ipaddr6)){
                $ipaddr6 = "Unavailable";
        }`

some interfaces don't have an IPv6 address

**Comment by VictorRobellini** [comment]
My only concern is that interfaces can have both IPv4 and IPv6 addresses. The best solution would be to display them both and just show null when things are null.

**Comment by opswhisperer** [comment]
Looks good to me with that check in place 
![2020-12-10_17-51-45](https://user-images.githubusercontent.com/4588615/101851499-87469f00-3b10-11eb-8909-2132c5521844.png)

**Comment by opswhisperer** [comment]
Looks good with that check in place

![2020-12-10_17-51-45](https://user-images.githubusercontent.com/4588615/101851639-c70d8680-3b10-11eb-95f6-26583e77db79.png)

**Comment by VictorRobellini** [comment]
I need to resync my local dashboard and plugins.  I'll be sure to include this.

Thanks

**Comment by VictorRobellini** [comment]
The only change I'll make is to change Unavailable to Unassigned.

Thanks

**Comment by travisboss** [comment]
> Looks good with that check in place
> 
> ![2020-12-10_17-51-45](https://user-images.githubusercontent.com/4588615/101851639-c70d8680-3b10-11eb-95f6-26583e77db79.png)

Any chance you could post what you did to add the info for a new dense grafana user?

**Comment by VictorRobellini** [comment]
This is added to the latest commit
