### ISSUE TITLE
Influxdb started without auth

### ISSUE THREAD

**Issue by mbentley** [VictorRobellini/pfSense-Dashboard#24]
The influxdb container isn't starting properly with auth.  Per the [Docker image documentation](https://hub.docker.com/_/influxdb), it requires the `INFLUXDB_HTTP_AUTH_ENABLED` env var to be set in order for any authentication specific env vars to work.

**Comment by VictorRobellini** [comment]
It most likely depends on the version of the image you are using.  The docker-compose I posted works with the version specified.

**Comment by mbentley** [comment]
It may have at one point but it doesn't appear to any more.  I just stood up the same stack using Docker Compose and the versions that exist in the example and compared it to my influxdb I verified auth was enabled on and tried to create a db:

Mine with auth:
```
# curl -i -XPOST https://influxdb.casa.mbentley.net:8086/query --data-urlencode "q=CREATE DATABASE mydb"
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Request-Id: 0e3cb26a-63bf-11eb-9c55-0242c0a802c9
Www-Authenticate: Basic realm="InfluxDB"
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.3
X-Request-Id: 0e3cb26a-63bf-11eb-9c55-0242c0a802c9
Date: Sun, 31 Jan 2021 12:22:59 GMT
Content-Length: 55

{"error":"unable to parse authentication credentials"}
```

Immediately after standing up via `docker-compose`:
```
# curl -i -XPOST http://builder-ssh.casa.mbentley.net:8086/query --data-urlencode "q=CREATE DATABASE mydb"
HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: 2c97d78c-63bf-11eb-8001-0242ac110003
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.10
X-Request-Id: 2c97d78c-63bf-11eb-8001-0242ac110003
Date: Sun, 31 Jan 2021 12:23:50 GMT
Transfer-Encoding: chunked

{"results":[{"statement_id":0}]}
```

**Comment by VictorRobellini** [comment]
According to your output:

`X-Influxdb-Version: 1.8.3`

According to the docker-compose I posted in the README which works on my system

`image: "influxdb:1.7.10-alpine"`

This was probably added in the 1.8 release, I don't know, I haven't checked the changelog.

**Comment by mbentley** [comment]
Ignore that because I change the version that I am actually running - that is just an example of what it looks like when authentication is actually working.  Look at the 2nd example where I stood it up using the compose in the readme: `X-Influxdb-Version: 1.7.10`

**Comment by VictorRobellini** [comment]
I noticed that after I reread your post and realized I completely missed it.

I don't keep up with all the changes in influx or grafana.  The configurations posted is what I am using.  I'm sharing it here to help other people get set up.  One of these days I'll update the stack.  I know there have been decent version bumps for both since I posted the configs, but it does everything I need it to do.

**Comment by mbentley** [comment]
Sorry, I just updated my comment right above your last one.  It's a quick fix, I can submit a PR to add the one line if it would be helpful.  I just wouldn't want people to be standing up InfluxDB without any auth.

**Comment by VictorRobellini** [comment]
FYI, I ended up doing a whole upgrade and did run into this.  I've since migrated my deployments to kubernetes.  Feel free to submit a PR for the docker-compose since I'm not longer going to be maintaining the docker-compose configs.
