### ISSUE TITLE
PfblockerNG

### ISSUE THREAD

**Issue by marcello1986** [VictorRobellini/pfSense-Dashboard#25]
Goodnight.
I downloaded without a template and did all the procedures as informed, I have the information, only the geolocation part is not working, would you have any tips?
Any particularities in the configuration of PfblockerNG?

**Comment by MatthewJSalerno** [comment]
Make sure you are using pfBlockerNG-devel

**Comment by VictorRobellini** [comment]
The main requirement is that you use the pfBlockerNG-devel package and not the pfBlockerNG package.
