### ISSUE TITLE
PFBlocker IPs - Incorrect

### ISSUE THREAD

**Issue by DustyArmstrong** [VictorRobellini/pfSense-Dashboard#26]
Hi Victor, 

Not really an issue but more a curiosity. 

I've noticed on all my firewalls (thanks for the design!) that the "PfBlocker IP - Total IPs Blocked" shows a random fairly large number in the thousands. It's easy to remove by mathing the incorrect counts away, but I'm curious if you've also seen this? A PfBlocker update maybe? 

Dusty.

**Comment by VictorRobellini** [comment]
I haven't looked into it, but I just added some updates and I'm getting
ready to commit.  Can you let me know what you changed so I can take a look
on my system?

Thanks

**Comment by DustyArmstrong** [comment]
Sure, it's the "Total IPs Blocked" item. 

The query `SELECT count("action") FROM "ip_block_log" WHERE ("host" =~ /^$Host$/) AND $timeFilter` returns 13,067 on my system, and approx 2,000 on another system I use this on. I have modified it to: 

`SELECT count("action") -13067 FROM "ip_block_log" WHERE ("host" =~ /^$Host$/) AND $timeFilter`

I don't know where these extra counts are coming from, and they don't appear to be consistent. The only consistency is that they aren't accurate. For clarity, when I have 0 blocked IPs it reads 13,067 (or 2,000 on my other dashboard for a separate firewall).

**Comment by bigjohns97** [comment]
I do not have this issue, @DustyArmstrong I would try deleting your pfblockerng logs as well as creating a new influxdb, I have seen this issue before whenever I had badly formatted data in my influxdb.

When I test this on my end the numbers change as I change the time range at the top.

For instance here is when I change to 5 minutes.
![image](https://user-images.githubusercontent.com/5262891/109991005-8bc5c280-7ccf-11eb-9b09-fef044c429a1.png)

**Comment by VictorRobellini** [comment]
@DustyArmstrong I'm in agreement with @bigjohns97.  If the issue was resolved by changing a math function within the influx query it would be a different story.  Based on the fix you needed to apply to get your count correct, it looks like the issue is with the data source rather than the query or graphing frontend.

**Comment by DustyArmstrong** [comment]
Thanks both. I figured as much but just found it odd it happened on two separate systems, one of which is running off a brand new influxdb created only yesterday. I suspect it is a problem with Pfblocker logs rather than influxdb based on that. I will try and fiddle with that and hopefully that fixes.

Closing this issue.
