### ISSUE TITLE
Issue with Temp, Gateway and Interface

### ISSUE THREAD

**Issue by travisboss** [VictorRobellini/pfSense-Dashboard#28]
Everything else seems to work but these three modules, I have the telegraf config in the additional config section and got all the WAN/LAN pieces setup, but not sure how to diagnose these pieces.

I am using a Netgate SG-2220, any thoughts tips from anyone?

Adding I am on version 2.5 pfsense and Telegraf 0.9_5

**Comment by travisboss** [comment]
Nevermind

**Comment by xekon** [comment]
Same issues here, what did you do to fix it?
