### ISSUE TITLE
Question: Throughput Graphs

### ISSUE THREAD

**Issue by setiseta** [VictorRobellini/pfSense-Dashboard#3]
On the Throughput graphs in the query, there is field(xx) derivative(10s)
For me it seems that it will display the pckts per 10 seconds, or am i wrong?
But i think mostly used in network graphs is pckts per second, so shouldnt it be derivative(1s)?

**Comment by VictorRobellini** [comment]
That's a great question and I'm not sure what the right answer is.  I most likely copied that from a doc I read while building this thing.  One thing I would look at is the sample rate for telegraf which is 10s by default.

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NET_README.md
In the above doc, It reads the following for a similar traffic query:

> The query uses the derivative function which calculates the rate of change between subsequent field values.

**Comment by setiseta** [comment]
I've tested today with a packets generator, and viewed the integrated pfsense graph on system/monitoring and compared the pps and mbps there with the one from the grafana dashboard.
and if I'm using derivative(1s) it seems to match good, but with the derivative(10s) its far too high.
so I've changed it for me to derivative(1s), maybe you could check this also?

the pfsense integrated graph has only a resolution from 1m so I've run the package generator a while to compare it.

**Comment by VictorRobellini** [comment]
I'll make the change in the dashboard and update the repo in a few.  The test you ran is a much better source of truth.

**Comment by VictorRobellini** [comment]
I've updated the graphs to use the 1s measurement.  Unless anyone else can provide better data to show that 1s is not correct, I'm going with your suggestion.

Thanks
