### ISSUE TITLE
Unable to edit 2nd and 3rd Lan Interface

### ISSUE THREAD

**Issue by travisboss** [VictorRobellini/pfSense-Dashboard#30]
I have three vlans setup and I can edit the main lan `igb1` but I am unable to edit the view for `igb.1.107` and `igb1.200` is there is setting in the `JSON` I can edit to allow editing these additional interfaces?  Reason being is I want to add ipv6 to the separate interfaces.

**Comment by MatthewJSalerno** [comment]
You can customize the interfaces in the list by modifying the $LAN_Interfaces variable

https://github.com/VictorRobellini/pfSense-Dashboard#grafana

> LAN_Interfaces - $LAN_Interfaces uses a regex to remove any interfaces you don't want to be grouped as LAN. The filtering happens in the "Regex" field. I use a negative lookahead regex to match the interfaces I want excluded. It should be pretty easy to understand what you need to do here. I have excluded igb0 (WAN) and igb1,igb2,igb3 (only used to host vlans).

**Comment by VictorRobellini** [comment]
You can customize the interfaces in the list by modifying the $LAN_Interfaces variable.  What does your $LAN_Interfaces regex look like?

https://github.com/VictorRobellini/pfSense-Dashboard#grafana

> LAN_Interfaces - $LAN_Interfaces uses a regex to remove any interfaces you don't want to be grouped as LAN. The filtering happens in the "Regex" field. I use a negative lookahead regex to match the interfaces I want excluded. It should be pretty easy to understand what you need to do here. I have excluded igb0 (WAN) and igb1,igb2,igb3 (only used to host vlans).

**Comment by travisboss** [comment]
All I have I have there `/^(?!igb0$)/` which is my wan interface.

**Comment by VictorRobellini** [comment]
If the regex is empty are all of the interfaces listed?
![image](https://user-images.githubusercontent.com/39597627/111005249-751b0d80-8358-11eb-9bcd-013439bedf24.png)

**Comment by travisboss** [comment]
Sorry for the delay.  Yes if I remove igb0 from the Regex it does add igb0.  To be clear my interfaces are all there I just cannot edit anything past the first LAN interface.

**Comment by VictorRobellini** [comment]
I'm not sure I understand.  Can you provide a screenshot that includes your regex?

**Comment by travisboss** [comment]
<img width="1142" alt="Screen Shot 2021-03-16 at 11 43 40 AM" src="https://user-images.githubusercontent.com/16948721/111347148-eacef400-864c-11eb-9d59-ad964fa093b3.png">
Here is a screenshot of the page which is showing the correct lan interfaces.

**Comment by VictorRobellini** [comment]
Is the issue that you can't modify the list of interfaces in the drop down list on the main dashboard?  Or are you trying to modify the panels for specific interfaces?  If you are trying to edit the panels for specific interfaces, you are going to need to get your hands dirty with Grafana.  The panels for the Lan interfaces are duplicated for each Lan interface and you can only modify the top Lan interface which will then be reflected for the other Lan interfaces.

**Comment by VictorRobellini** [comment]
No response.
