### ISSUE TITLE
Compatibility with influxdb 2.0

### ISSUE THREAD

**Issue by faandg** [VictorRobellini/pfSense-Dashboard#33]
Hi,

Just wondering, any plans to switch to Flux queries to support influxdb 2.0 or are we waiting for influxdb 2.0 to also support influxQL (somewhere later this year)?

Thanks for creating such an amazing dashboard btw.

**Comment by VictorRobellini** [comment]
I haven't messed with flux but I've read good and bad things about it. I'm not a developer and outside of this project, I don't work with Influx, which limits my time learning it. If I had the time to invest to learn more about Influx I would focus on structural issues first. Better indexing, TSI, and [downsampling and retention](https://docs.influxdata.com/influxdb/v1.8/guides/downsample_and_retain/). Currently, the database will just grow until you run out of space.  Fixing those issues would be a priority over flux.  I would love to take advantage of the join capabilities and other bells and whistles, but first I would want to make sure the data itself is in a good place.  My current solution is to just drop the db when it gets to be too large, which sucks.

**Comment by VictorRobellini** [comment]
Aside from the above commentary, it looks like Influxdb 2.0 supports InfluxQL. I can't say if you could just drop it in and it would work, but it's very probable that it would just work.

**Comment by faandg** [comment]
I can certainly respect that choice.

I ran into this bit of information
![image](https://user-images.githubusercontent.com/5772741/111878152-411e9880-89a7-11eb-9df7-44d36751e1cd.png)
This was a while ago though so it could be it now supports InfluxQL and the errors I saw when I tested it were related to something else.
I'll take another look soon.

**Comment by faandg** [comment]
As per the screenshot, you are correct and influxdb 2.0 should now support InfluxQL. 

![image](https://user-images.githubusercontent.com/5772741/111880935-7bd7ff00-89ae-11eb-86f1-9b9505bbec7f.png)

However, the problem seems to be that the Grafana datasource configuration does not allow me to select InfluxQL and connect to an InfluxDB v2.0 using v2 configuration settings. It assumes that, because I want to use InfluxQL, that I also want to connect to an InfluxDB 1.x:

![image](https://user-images.githubusercontent.com/5772741/111880779-affef000-89ad-11eb-80df-9238beb3d50f.png)

Choosing **InfluxQL** changes the "InfluxDB details" section to:

![image](https://user-images.githubusercontent.com/5772741/111880833-fb190300-89ad-11eb-8bee-2a23241f4498.png)

So selecting InfluxQL prevents you from using InfluxDB 2's token, organization and bucket configuration.

In contrast, selecting **Flux** gives you token, organization and bucket configuration:
![image](https://user-images.githubusercontent.com/5772741/111881027-f143cf80-89ae-11eb-93d5-5900b9e6252c.png)

I will open an issue for this on the Grafana side because I believe it should be made possible.

**Comment by VictorRobellini** [comment]
Thanks for the update.  Interesting find.  Can you post a link to your issue?  I'm interested in seeing how it plays out.

**Comment by faandg** [comment]
Here you go: https://github.com/grafana/grafana/issues/32183
I imagine it might take some time though, seeing the amount of open issues at the moment.

**Comment by faandg** [comment]
They basically said "hey this is possible, here's a blog" and closed the ticket.
Took me a while to figure everything out though. Could write another blog about this :)

In the InfluxDB v2 UI:
1) Create an admin user, organization (I use 'mist') and bucket (I use 'pfsense')
2) Data-> Tokens, generate a READ token for grafana
3) Data-> Tokens, generate a READ/WRITE token for telegraf (WRITE alone might be sufficient but haven't tested it)

In pfsense:
4) The telegraf package UI does not support outputting to v2 yet, so the output needs to be added via the 'Additional configuration for Telegraf'
Services -> Telegraf, remove everything related to output and deselect influxDB (`ctrl` + click)

![image](https://user-images.githubusercontent.com/5772741/112046984-f76fb280-8b4c-11eb-9460-3b1ee768d2da.png)

Take the [Telegraf config from this repo](https://github.com/VictorRobellini/pfSense-Dashboard/blob/master/config/additional_config.conf) and add the output part:
```
[[outputs.influxdb_v2]]
  urls = ["http://INFLUXDB_HOST:8086"]
  token = "TOKEN"
  organization = "mist"
  bucket = "pfsense"
```
! Replace TOKEN with the token from step 3 and INFLUXDB_HOST with your InfluxDB v2 host.

5) InfluxDB v2 uses organization + bucket and v1 uses database + retention policy (dbrp).
Grafana expects we configure a v1 object when using InfluxQL as query language.
To make this work we have to create an object in InfluxDB which is basically a mapping between v2 and v1 so it also exposes a v1 endpoint. 
This cannot be done in the InfluxDB UI afaik, you need to create this mapping using the [API](https://docs.influxdata.com/influxdb/v2.0/reference/api/) or the [CLI](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/).
I used the CLI. 
a) create config to authenticate via CLI (use the organization and admin user's token you created in step 1)
```
influx config create --config-name influxadm_config \
  --host-url http://INFLUXDB_HOST:8086 \
  --org mist \
  --token TOKEN \
  --active
```
b) create the mapping (you can get the bucket-id and the org-id from the InfluxDB UI as well):
```
influx v1 dbrp create \
  --db pfsense \
  --rp autogen \
  --bucket-id 00oxo0oXx000x0Xo \
  --org-id 00oxo0oXx000x0Xo \
  --default
```
_Side note_: You need to specify an rp (retention policy). On my first attempt I created one called pfsense-rp, but after loading the dashboard, the errors showed me that some panels were expecting an rp called 'autogen', which is the default rp in InfluxDB v1. Hence on my second attempt I named it autogen and the query errors were gone. I have no clue what the actual retention is on this thing or if it differs from the bucket's settings.

6) Creating the Grafana datasource
- set a name
- set your query language to InfluxQL
- set the URL
- set a custom HTTP Header '**Authorization**' with value '**Token <actual token you created in step 2>**' 
(I messed up this part and it took me a while to figure out)
- set the database name to the name of your bucket
- you don't need user and password since we're using a token
- HTTP GET or POST, both work for this dashboard
- test and save

And holy ****, it works.

![image](https://user-images.githubusercontent.com/5772741/112050088-bd081480-8b50-11eb-81ff-d3ac0144264b.png)

PS: I am unable to test the pfBlocker panel because I don't have pfBlocker active at the moment.

**Comment by vavsaftoiu** [comment]
Hi there,

Thanks a lot for sorting this out. Incredible work and really nice that you shared the solution.

**Comment by lgwapnitsky** [comment]
I've been working on rewriting this in Flux, and have forked the repo. See issue #44  for more info

**Comment by foreverlate** [comment]
What to fill in for 
![image](https://user-images.githubusercontent.com/92173313/201480678-4a9729cc-4fdb-4152-bc8b-531bd24d141a.png)

In grafana v9.2.1 I am getting error after following all the steps
![image](https://user-images.githubusercontent.com/92173313/201480694-856c4495-18d8-407a-8de2-5598d3e0bf36.png)

**Comment by rpclarke** [comment]
@faandg - Thank you so much! I spent hours yesterday morning trying to figure this out and came across this post. This worked for me.

**Comment by jbcodemonkey** [comment]
Thank you! Still works. Happy 2025!
