### ISSUE TITLE
Receiving "Error in Plugin" output

### ISSUE THREAD

**Issue by 73udz** [VictorRobellini/pfSense-Dashboard#4]
When attempting to use the package PFSense fails to run with the below output error

I have verified all files have 555 set. Influx is outputting default information without any issue. When attemtping to output log files I just receive the below error. I then routed to testing telegrafs config with the telegraf.conf --test command to get the below output

```
2020-05-03T01:25:31Z E! [inputs.exec] Error in plugin: exec: fork/exec /usr/local/bin/telegraf_gateways.py: no such file or directory for command '/usr/local/bin/telegraf_gateways.py':
2020-05-03T01:25:31Z E! [inputs.exec] Error in plugin: metric parse error: expected tag at 1:58: "temperature,sensor=tz0,host=host-pfsense.my-local.net"
2020-05-03T01:25:31Z E! [inputs.exec] Error in plugin: exec: exit status 255 for command '/usr/local/bin/telegraf_pfinterface.php':
```

Error from Log:
`daemon: process already running, pid: 41722`

**Comment by VictorRobellini** [comment]
If it's complaining about "Process already running" chances are you didn't kill the telegraf pid before trying to debug.

Also, have you verified that this file exists:

> no such file or directory for command '/usr/local/bin/telegraf_gateways.py

**Comment by 73udz** [comment]
I verified all the files existed and were named properly. They are all in the same directory:

![Capture](https://user-images.githubusercontent.com/39133841/80935045-c5cdeb80-8dc2-11ea-98f7-8fd5b814047f.PNG)


I have tried using the Kill -HUP and the PID of the Telegraf daemon and that is when it outputs the Process already running.

**Comment by 73udz** [comment]
Also want to add, I have go through and ran the below commands and received the below outputs to verify each file.

```
[2.4.5-RELEASE][admin@campos-sense.campos-local.net]/root: php /usr/local/bin/telegraf_pfinterface.php
interface,host=campos-sense.campos-local.net,name=igb0,ip_address=86.10.201.112,mac_address=00:e0:67:1b:67:f8,friendlyname=WAN,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb1,ip_address=192.168.1.1,mac_address=00:e0:67:1b:67:f9,friendlyname=RTR,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb3.51,ip_address=172.16.51.1,mac_address=00:e0:67:1b:67:fb,friendlyname=MASTER_SWITCH_MGMT,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb3.200,ip_address=172.16.200.1,mac_address=00:e0:67:1b:67:fb,friendlyname=IDRACMANAGEMENT,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb3.60,ip_address=172.16.60.1,mac_address=00:e0:67:1b:67:fb,friendlyname=VLAN60_SERVERS,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb2,ip_address=172.16.61.1,mac_address=00:e0:67:1b:67:fa,friendlyname=PIHOLE,source=pfconfig status=0
interface,host=campos-sense.campos-local.net,name=igb3.70,ip_address=172.16.70.1,mac_address=00:e0:67:1b:67:fb,friendlyname=VLAN70_SERVERS2,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb3.100,ip_address=172.16.100.1,mac_address=00:e0:67:1b:67:fb,friendlyname=VLAN100_PRIV,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb3,ip_address=Unassigned,mac_address=00:e0:67:1b:67:fb,friendlyname=MASTERSWITCH,source=pfconfig status=1
interface,host=campos-sense.campos-local.net,name=igb3.10,ip_address=172.16.10.1,mac_address=00:e0:67:1b:67:fb,friendlyname=VLAN10_ACCESS,source=pfconfig status=1

```

```
[2.4.5-RELEASE][admin@campos-sense.campos-local.net]/root: python3.7 /usr/local/bin/telegraf_gateways.py
gateways,gateway_name=WAN_DHCP rtt=167.75,rttsd=78.0,loss=0i

```


```
 [2.4.5-RELEASE][admin@campos-sense.campos-local.net]/root: sh /usr/local/bin/telegraf_temperature.sh
: not foundbin/telegraf_temperature.sh:
 degrees=26.9ensor=tz0,host=campos-sense.campos-local.net

```

The only one that appears to be having issues is the temp script but it is outputting some info

**Comment by VictorRobellini** [comment]
Is this a fresh 2.4.5 install?  The one thing that had me going nuts was that when you execute things from a shell vs from telegraf, the environment is different.

`/usr/local/bin/telegraf --test -config=./test.conf`

**Comment by 73udz** [comment]
Its a fresh update. I just recently updated  from 2.4.4 to 2.4.5. 

I ran the files from shell to verify paths and that the files are readable and in the location defined in the telegraf config, and that they were executable without errors. 

The first post showing Errors in plugin is when executed from the --test -config.

**Comment by VictorRobellini** [comment]
In that case, I think it's best to get the debug logs from telegraf.

**Comment by 73udz** [comment]
I have resolved the issue. My fix for anyone who find the same issue was defining php and python3.7 in the Additional configuration for Telegraf. See Below:

```
[[inputs.exec]]
   commands = [
     "php /usr/local/bin/telegraf_pfinterface.php",
     "python3.7 /usr/local/bin/telegraf_gateways.py",
     "sh /usr/local/bin/telegraf_temperature.sh"
   ]
   data_format = "influx"
```
