### ISSUE TITLE
"Gateway RTT - All" Not showing 

### ISSUE THREAD

**Issue by nobeldwarf** [VictorRobellini/pfSense-Dashboard#43]
Am I missing something as I can not get Gateway RTT to work see screenshots below?

![image](https://user-images.githubusercontent.com/6348967/134137512-fbf4a903-89b1-41c9-bbda-1b40482ec80a.png)

![image](https://user-images.githubusercontent.com/6348967/134137680-5b28737d-891e-4a72-b12b-a7dcf2d5f0d5.png)

![image](https://user-images.githubusercontent.com/6348967/134137870-af413d8d-4769-4757-86e4-bfb662290371.png)

**Comment by naiz0** [comment]
I changed from "mean(rtt)" to "mean(delay)" and it works.

**Comment by nobeldwarf** [comment]
> I changed from "mean(rtt)" to "mean(delay)" and it works.

Thanks it's working now.
