### ISSUE TITLE
Hi, great dashboard, but can't make it work

### ISSUE THREAD

**Issue by VictorRobellini** [VictorRobellini/pfSense-Dashboard#45]
-- Moving to it's own issue
@sbeechee

Hi, great dashboard, but can't make it work
Everything installed by the way it is documented, but still no data can be read from Grafana (Telegraf is writing in Influx and the database is called pfsense as the example).
Is something missed in the documentation or is just plug and play as showed?
Made some changes to the configuration because in Netgate SG-1100 the temperature can't be readed from the sysctl because there's no hw.acpi and also [[inputs.swap]] was producing some errors (can't read that variable of the system)

Regards
Sebastian

_Originally posted by @sbeeche in https://github.com/VictorRobellini/pfSense-Dashboard/issues/38#issuecomment-949915323_

**Comment by lgwapnitsky** [comment]
I've been working on rewriting this in Flux, and have forked the repo. See issue #44  for more info

**Comment by VictorRobellini** [comment]
The issue here in influx 2.x and the use of influxQL connections in my dashboard.
