### ISSUE TITLE
no pfBlocker Data, no ip_block.log

### ISSUE THREAD

**Issue by 2EyeTec** [VictorRobellini/pfSense-Dashboard#5]
I'm not receiving any pfBlocker Data (verified with show measurements). I think it's because of the additional_config.conf. 
telegraf.log:

> D!  Grok no match found for: "DNSBL Reject HTTPS,May 03 14:37:48,mobile.pipe.aria.microsoft.com" 

Here is how the entries in my dnsbl.log look like:

>   DNSBL Reject HTTPS,May 03 12:31:38,e.crashlytics.com

I don't have a ip_block.log on my system, which is also reported as an error in the telegraf.log:

> E! [inputs.logparser] Error in plugin: open /var/log/pfblockerng/ip_block.log: no such file or directory

Can you help me? Thanks!

**Comment by VictorRobellini** [comment]
My guess is that you are running  pfBlockerNG rather than  pfBlockerNG-devel.

**Comment by 2EyeTec** [comment]
Yes, you're right. I was about to have the same idea ;-). Installed pfBlockerNG-devel and now it's working. Thanks a lot!
