### ISSUE TITLE
Error loading config file /usr/local/bin/telegraf_pfifgw.php: Error parsing data: line 2: invalid TOML syntax

### ISSUE THREAD

**Issue by DieterUcll** [VictorRobellini/pfSense-Dashboard#51]
Im executing this : telegraf --test --config /usr/local/bin/telegraf_pfifgw.php in the command prompt in pfsense to test the script.
Im having the error that you can see in the subject. Config comes from the file you provided.

**Comment by RobertoMarcelino** [comment]
Same error.

**Comment by vinhthai1989** [comment]
same error

**Comment by faandg** [comment]
The `--config` flag on Telegraf is used to pass a telegraf.conf file, not a php script.
You cannot test it this way.

Use the script inside a Telegraf `exec` plugin: https://github.com/VictorRobellini/pfSense-Dashboard/blob/master/config/additional_config.conf

**Comment by DieterUcll** [comment]
writing this in command prompt pfsense /usr/local/bin/telegraf_pfifgw.php did work.
I can verify that i see my interfaces, both lan and wan. I'm now also receiving the data in InfluxDB2.
Now i need to fix my grafana dashboard.
