### ISSUE TITLE
How to enable unbound stats?

### ISSUE THREAD

**Issue by travisboss** [VictorRobellini/pfSense-Dashboard#56]
I have enabled `unbound_lite.sh` and changed to that `sh` file in the telegraf plugin.  But I am wondering on how to actually display this data?

Thanks!

**Comment by faandg** [comment]
From the readme:
> Unbound stats - Plugin and config included and working but not implemented
Seems like no dashboard panels have been created (yet) for unbound.

**Comment by bigjohns97** [comment]
I have some panels which show cache hit / miss ratios, how would you like the data? JSON or you just want to see the queries?

**Comment by wrightsonm** [comment]
@bigjohns97 i'd happily add your changes.  
Feel free to raise a PR on my fork which is using InfluxDB v2 and now using Flux rather than influxql: https://github.com/wrightsonm/pfSense-Dashboard

@faandg perhaps we should come up with a plan to collaborate and create a single dashboard as we currently have 3 variants.

**Comment by wrightsonm** [comment]
@bigjohns97 have made a start on adding some unbound charts here:
 https://github.com/wrightsonm/pfSense-Dashboard
 
 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/6232774/155386076-a9e2bc8b-71b0-4614-ac5f-c91feee039c6.png">

**Comment by faandg** [comment]
@wrightsonm the easiest solution I can think of would be for each of you maintain a branch in a single repo and to add clarification in the main branch readme with screenshots for each variant. 
The only difference between them would be the dashboard json. 

Then you would have to agree on repository ownership/access rights and I should not be a part of that discussion so it's really up to you guys.
