### ISSUE TITLE
Telegraf-Temperature on APU Board

### ISSUE THREAD

**Issue by peterge1998** [VictorRobellini/pfSense-Dashboard#6]
First of all, thanks for putting the dashboard together!
I run pfsense on an [PC Engines APU Board](https://www.apu-board.de/produkte/apu4d4.html). However, the temperature is not working out of the box.
Executing /usr/local/bin/telegraf_temperature.sh gives this result:
```
temperature,sensor=cpu3,host=pfSense.domain.local degrees=55.1
temperature,sensor=cpu2,host=pfSense.domain.local degrees=55.1
temperature,sensor=cpu1,host=pfSense.domain.local degrees=55.1
temperature,sensor=cpu0,host=pfSense.domain.local degrees=55.1
sysctl: unknown oid 'hw.acpi.thermal'
```
Could you please post the expected output from you device so i can compare the results and find out what i need to adjust on my system?
Thank you very much!

**Comment by VictorRobellini** [comment]
My guess is that your APU doesn't have acpi thermal sensors.  I don't own and have never worked with those systems.  Just comment out or delete the line in the telegraf_temperature.sh that greps for acpi and the error should go away.  There may be other temp sensors you can use but you would have to check for yourself by poking around sysctl or reading the board specs.

**Comment by peterge1998** [comment]
In case some has the same problem, setting Thermal Sensors under     System > Advanced > Miscellaneous > Cryptographic & Thermal Hardware to this value works:
![image](https://user-images.githubusercontent.com/47355238/81414222-eee5d780-9146-11ea-94d3-a3870ea851b4.png)
The first query in `telegraf_temperature.sh` works fine with the Grafana Dashboard:
`sysctl dev.cpu | fgrep temperature | tr -d '[:blank:]' | awk -v HOST="$HOSTNAME" -F '[.:]' '{print "temperature,sensor="$2$3",host="HOST" degrees=" $5"."substr($6, 1, length($6)-1)}'`
![image](https://user-images.githubusercontent.com/47355238/81414353-248ac080-9147-11ea-826d-64f0e2f4b24e.png)
I uncommented the `sysctl hw.acpi.thermal ` line.
